### ISSUE TITLE
Unavailable images cause listing servers to fail

### ISSUE THREAD

**Issue by jcgruenhage** [HenningHolmDE/hcloud-rust#11]
We're calling `hcloud::apis::servers_api::list_servers` on a project, where a server has it's image set to be "unavailable", because we restored it from a snapshot that has since been deleted. This causes serde to fail parsing it. The issue downstream is https://gitlab.com/famedly/company/devops/tools/hcloud-prom-filesd/-/issues/4, ftr. This needs patching in the unofficial OpenAPI spec (https://github.com/MaximilianKoestler/hcloud-openapi/issues/14), or switching to the official OpenAPI spec, which does this correctly.

**Comment by HenningHolmDE** [comment]
Thanks for reporting the issue.

We now releases a new version (0.8.0) of the crate that updates everything to the current state of the API and should fix your issue as well.

Please test the new version in your project and let me know if everything works as expected.

**Comment by jcgruenhage** [comment]
Sorry, forgot to report back: Works as expected!
