### ISSUE TITLE
Can't ignore paths in rustfmt without Nightly

### ISSUE THREAD

**Issue by good-praxis** [HenningHolmDE/hcloud-rust#13]
When running `cargo fmt`, I get the following errors:

```
Warning: can't set `ignore = IgnoreList { path_set: {"src/apis", "src/models"}, rustfmt_toml_path: "" }`, unstable features are only available in nightly channel.
Warning: can't set `ignore = IgnoreList { path_set: {"src/models", "src/apis"}, rustfmt_toml_path: "" }`, unstable features are only available in nightly channel.
Warning: can't set `ignore = IgnoreList { path_set: {"src/apis", "src/models"}, rustfmt_toml_path: "" }`, unstable features are only available in nightly channel.
Warning: can't set `ignore = IgnoreList { path_set: {"src/apis", "src/models"}, rustfmt_toml_path: "" }`, unstable features are only available in nightly channel.
Warning: can't set `ignore = IgnoreList { path_set: {"src/models", "src/apis"}, rustfmt_toml_path: "" }`, unstable features are only available in nightly channel.
```

Is there a reason we opt to not format the generated files? Doesn't it make them easier to parse for the human eye? And since the templates don't change on every code change, it's not like every commit will update the formatting of the templates

**Comment by kpcyrd** [comment]
I think this is related to https://github.com/rust-lang/rustfmt/pull/4139 and https://github.com/rust-lang/rustfmt/issues/3395

**Comment by HenningHolmDE** [comment]
Thanks for reporting the issue.

> Is there a reason we opt to not format the generated files?

While I still know I excluded the generated files on purpose (and therefore had to switch fmt to nightly for that), I cannot remember why I thought that not formatting the generated code was a good idea. :(

So I guess we can add `cargo fmt` to the post-processing steps in `generate_api_code.sh` and get rid of the exclude.
