### ISSUE TITLE
ID-type mismatch

### ISSUE THREAD

**Issue by lpotthast** [HenningHolmDE/hcloud-rust#22]
`hcloud::models::network::Network` contains `pub id: i64`

but

`hcloud::models::create_server_request::CreateServerRequest` requires `pub networks: Option<Vec<i32>>`

Does the id-type-mismatch already come from the Hetzner API or is something wrong in the generator?

There are more places where ID types are inconsistent. Having to downcast at these points is extremely annoying.

**Comment by MaximilianKoestler** [comment]
@HenningHolmDE I have just released v0.16.0 of the spec that addresses this issue. It looks good from what I can tell but I have not performed any testing with generated code.

According to Hetzner, they will start actually using IDs between 2^32 and 2^52-1 from September 1st onwards, so this is a bit urgent.

**Comment by HenningHolmDE** [comment]
Thanks for reporting the issue, @lpotthast !

This is definitely something that needs to be fixed before Hetzner will start using the new IDs.

I just created a commit updating to the new spec release and could not see any issues with the generated code. As mentioned in MaximilianKoestler/hcloud-openapi#28, there might be one occurrence left, that I would like to fix as well in a new release.

Feel free to start some testing on the unreleased version, if this resolves your issues.

**Comment by HenningHolmDE** [comment]
I have just released version 0.16.0 of the crate which should fix the issue.

If we overlooked any ID field types in the process, feel free to reopen the issue.

Thanks again for reporting the issue, this helps a lot!
