### ISSUE TITLE
New api Version!

### ISSUE THREAD

**Issue by devmaxde** [HenningHolmDE/hcloud-rust#23]
Since Today is a new Api version online. This breaks hcloud::apis::server_types_api::list_server_types and some more stuff

https://status.hetzner.com/de/incident/682c742f-1dc0-40da-83ed-be2d89a2a43b

**Comment by devmaxde** [comment]
By now there is even an official OpenAPI definition:

https://docs.hetzner.cloud/spec.json

**Comment by HenningHolmDE** [comment]
Thanks for letting me know. I will try to work on a fix soon.

As for the official OpenAPI definition: The official API definiton is already the basis for [hcloud-openapi](https://github.com/MaximilianKoestler/hcloud-openapi) from which `hcloud-rust` is generated, but we kept several schema transformations (e.g. component extractions) in place to improve the result of the generated API code.

**Comment by devmaxde** [comment]
Any Update on that? It's a breaking change. Users won't be able to use some parts of this crate right now.

**Comment by HenningHolmDE** [comment]
Version [0.20.0](https://crates.io/crates/hcloud/0.20.0) of `hcloud` has now been released to crates.io, hopefully adressing all of the issues.

@devmaxde Thank your for your patience, if you run into any problems, please let me know.

Many thanks to @MaximilianKoestler for the support on bringing the API specification up to date again.
