### ISSUE TITLE
Failure to parse response to create_server because of missing field

### ISSUE THREAD

**Issue by firstdorsal** [HenningHolmDE/hcloud-rust#27]
https://docs.hetzner.cloud/changelog#2024-11-05-deprecated-fields-for-traffic-information-removed
```
error in serde: missing field `included_traffic` at line 86 column 5
```

**Comment by HenningHolmDE** [comment]
Thanks for reporting the issue. Seems this is due to an API update Hetzner released the last days.

Unfortunately, I'm currently buried in work, I'll try to get around to this on the weekend.

**Comment by MaximilianKoestler** [comment]
@HenningHolmDE I just synced the changes to https://github.com/MaximilianKoestler/hcloud-openapi (no release yet, but you can test on **main** (also renamed the default branch while I was at it 😉 )

**Comment by HenningHolmDE** [comment]
@MaximilianKoestler The spec version from your main branch seems to work fine for fixing this. Would you be able to create a release shortly?

**Comment by MaximilianKoestler** [comment]
> @MaximilianKoestler The spec version from your main branch seems to work fine for fixing this. Would you be able to create a release shortly?
Done!

**Comment by HenningHolmDE** [comment]
@firstdorsal With the new **0.21.0** release of hcloud-rust, your issue should now be fixed. If the error still occurs, please feel free to reopen this issue.

@MaximilianKoestler Thank you for the fast response and the support!

**Comment by firstdorsal** [comment]
thank you for the quick fix!
