### ISSUE TITLE
Update for tokio 1

### ISSUE THREAD

**Issue by jcgruenhage** [HenningHolmDE/hcloud-rust#8]
I've been meaning to update one of our projects that uses hcloud to tokio 1 (1.4.0 to be specific), but while it compiles, I can run the thing anymore. As soon as I try to do any hcloud api requests the thing crashes. Does updating the `reqwest` dependency require an update from the openapi generator people, or is that something you can do yourselves?

**Comment by HenningHolmDE** [comment]
Thanks for reporting the issue!

I'll take a look into it over the weekend and will see what I can do.

**Comment by HenningHolmDE** [comment]
I just published version 0.4.0 using updated dependencies. Does this solve the issue?

**Comment by jcgruenhage** [comment]
yep, works now! Thanks :)
